# docsifyを使用してGitHub Pagesにデプロイするためのワークフロー

name: Deploy Docsify to GitHub Pages

# ワークフローの実行タイミングを制御します
on:
  # "master"ブランチへのプッシュまたはプルリクエストイベントでワークフローをトリガーします
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Actionsタブから手動でこのワークフローを実行することを許可します
  workflow_dispatch:

# ワークフロー実行は、順次または並行して実行できる1つ以上のジョブで構成されます
jobs:
  build:
    # ジョブが実行されるランナーの種類
    runs-on: ubuntu-latest

    # ステップは、ジョブの一部として実行されるタスクのシーケンスを表します
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # docsify-cliのインストール
      - name: Install docsify-cli
        run: npm install -g docsify-cli

      # .nojekyllファイルの作成
      - name: Create .nojekyll file
        run: |
          # .nojekyllファイルが存在することを確認（GitHub Pagesでアンダースコアで始まるファイルを処理するため）
          touch .nojekyll

      # リポジトリファイルの確認
      - name: List repository files
        run: ls -la

      # アーティファクトのアップロード（リポジトリ全体）
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # リポジトリ全体をアップロード
          path: '.'

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
